export const SPHERES_DATA = [
  {
    id: "immobilier",
    title: "1. IMMOBILIER & HABITAT",
    description: "Client commun : Le propriétaire (achat, vente, travaux).",
    trades: [
      "Agent Immobilier",
      "Courtier en prêt",
      "Gestionnaire de patrimoine",
      "Diagnostiqueur",
      "Architecte d'intérieur",
      "Maître d'œuvre / Rénovation",
      "Cuisiniste / Bainiste",
      "Expert Domotique / Électricien",
      "Paysagiste / Entretien jardin",
      "Pisciniste",
      "Notaire",
      "Déménageur",
      "Conciergerie Airbnb",
      "Photographe Immobilier",
      "Chasseur Immobilier",
      "Avocat fiscaliste",
      "Courtier en Assurances (habitation)",
      "Menuisier (portes, fenêtres, vérandas)",
      "Installateur Panneaux Solaires / PAC",
      "Home Stager (décoration pour vente)",
    ],
  },
  {
    id: "business",
    title: "2. BUSINESS & DIGITAL (B2B)",
    description: "Client commun : Le dirigeant qui veut de la croissance et de l'efficacité.",
    trades: [
      "Webdesigner",
      "Expert SEO",
      "Copywriter (Rédacteur)",
      "Community Manager",
      "Photographe / Vidéaste Corporate",
      "Agence Pub (Ads)",
      "Expert Tunnel de vente",
      "Coach Business / Mentor",
      "Expert Comptable",
      "Recruteur / Chasseur de têtes",
      "Consultant RH",
      "Développeur Web",
      "Expert Cybersécurité",
      "Graphiste / Identité visuelle",
      "Imprimeur local",
      "Consultant CRM / Data",
      "Expert Automatisation (No-code)",
      "Commercial Freelance",
      "Growth Hacker",
      "Community Builder (réseaux de membres)",
    ],
  },
  {
    id: "bien-etre",
    title: "3. BIEN-ÊTRE & SERVICES",
    description: "Client commun : Le particulier qui investit sur lui-même.",
    trades: [
      "Coach Sportif",
      "Nutritionniste / Diététicien",
      "Ostéopathe",
      "Prof de Yoga / Pilates",
      "Naturopathe",
      "Magasin Bio / Producteur local",
      "Coiffeur / Barbier",
      "Esthéticienne / Prothésiste ongulaire",
      "Sophrologue",
      "Psychologue / Thérapeute",
      "Wedding Planner",
      "Traiteur",
      "Photographe (Mariage / Famille)",
      "Coach de vie",
      "Hypnothérapeute",
      "Masseuse bien-être / Spa",
      "Kinésiologue",
      "Acupuncteur",
      "Personal Shopper / Conseil en image",
      "Éducateur canin",
    ],
  },
  {
    id: "commerce",
    title: "4. COMMERCE & LOCAL",
    description: "Crucial pour le networking local à Bordeaux.",
    trades: [
      "Restaurateur",
      "Caviste",
      "Gérant de salle de sport",
      "Fleuriste",
      "Chocolatier / Pâtissier",
      "Propriétaire de Gîte / Chambre d'hôtes",
      "Bijoutier",
      "Opticien",
      "Libraire",
      "Gérant de Coworking",
      "Tailleur / Boutique de vêtements",
      "Loueur de voitures (Luxe ou utilitaires)",
      "Assureur local (Pro & Perso)",
      "Organisateur d'événements locaux",
      "Agent de voyage (indépendant)",
      "Courtier en énergie (pour commerces)",
      "Expert en signalétique (enseignes)",
      "Nettoyage de bureaux / Vitres",
      "Torréfacteur",
      "Coach en prise de parole / Conférencier",
    ],
  },
  {
    id: "conseil",
    title: "5. CONSEIL & DROIT",
    description: "Pour les dossiers à haute valeur ajoutée.",
    trades: [
      "Avocat Droit des Affaires",
      "Avocat Droit du Travail",
      "Conseil en Propriété Intellectuelle",
      "Courtier en Crédit Professionnel",
      "Consultant RSE",
      "Traducteur Interprète (Business)",
      "Expert en levée de fonds",
      "Consultant en Cybersécurité (Audit)",
      "Commissaire aux comptes",
      "Consultant en gestion de crise",
      "Courtier en Flotte de véhicules",
      "Conseil en Immobilier d'entreprise",
      "Formateur certifié Qualiopi",
      "Consultant en Logistique / Supply Chain",
      "Graphologue / Expert en recrutement",
      "Huissier de justice",
      "Arbitre / Médiateur",
      "Expert en transmission d'entreprise",
      "Consultant en Intelligence Artificielle",
      "Agent d'artistes ou de sportifs",
    ],
  },
];
