BEGIN;

INSERT INTO public.sector_vocabulary (
  sector_id,
  label,
  pipeline_steps,
  terms,
  message_templates,
  is_active
)
VALUES
  ('coach_sport','Coach sportif',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('coach_biz','Coach business',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('coach_vie','Coach de vie',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('coach_parental','Coach parental',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('coach_couple','Coach de couple',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('coach_carriere','Coach carriere',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('coach_confiance','Coach confiance en soi',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('coach_mental','Preparateur mental',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('coach_prise_parole','Coach prise de parole',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('mentor_entrepreneur','Mentor entrepreneur',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('hypno','Hypnotherapeute',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('sophrologie','Sophrologue',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('psycho','Psychologue liberal',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('psy_therapeute','Psychotherapeute',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('emdr','Therapeute EMDR',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('eft','Praticien EFT',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('kine','Kinesitherapeute',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('osteo','Osteopathe',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('chiro','Chiropracteur',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('naturo','Naturopathe',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('acupuncture','Acupuncteur',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('reflexo','Reflexologue',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('massage','Praticien massage bien-etre',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('reiki','Praticien Reiki',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('yoga','Professeur de yoga',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('meditation','Instructeur meditation',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('pilates','Professeur de Pilates',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('dietetique','Dieteticien',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('nutrition','Nutritionniste',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('micronutrition','Micronutritionniste',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('orthophoniste','Orthophoniste',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('psychomotricien','Psychomotricien',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('art_therapie','Art-therapeute',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('musicotherapie','Musicotherapeute',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('ayurveda','Praticien Ayurveda',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('estheticienne','Estheticienne',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('coiffeur','Coiffeur independant',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('maquilleuse','Maquilleuse professionnelle',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('onglerie','Prothesiste ongulaire',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('epilation_laser','Praticien epilation laser',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('tatoueur','Tatoueur',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('permanent_makeup','Maquillage permanent',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('spa','Gerant de spa independant',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('personal_stylist','Personal stylist',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('relooking','Conseiller relooking',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('immo','Agent immobilier',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('chasseur_immo','Chasseur immobilier',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('courtier_immo','Courtier immobilier',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('gestionnaire_locatif','Gestionnaire locatif',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('diagnostiqueur','Diagnostiqueur immobilier',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('archi_interieur','Architecte d interieur',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('decorateur','Decorateur d interieur',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('home_stager','Home stager',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('constructeur','Constructeur independant',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('paysagiste','Paysagiste',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('courtier_credit','Courtier en credit',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('cgp','Conseiller en gestion de patrimoine',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('courtier_assurance','Courtier assurance',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('expert_comptable','Expert-comptable',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('comptable','Comptable independant',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('conseiller_fiscal','Conseiller fiscal',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('conseiller_retraite','Conseiller retraite',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('investisseur_immo','Formateur investissement immo',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('avocat','Avocat independant',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('notaire','Notaire',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('huissier','Huissier de justice',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('mediateur','Mediateur',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('juriste','Juriste freelance',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('formateur','Formateur professionnel',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('prof_particulier','Professeur particulier',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('formatrice_digitale','Formateur digital / e-learning',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('coach_langues','Professeur de langues',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('consultant_rh','Consultant RH',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('outplacement','Consultant outplacement',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('bilan_competences','Consultant bilan de competences',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('consultant_marketing','Consultant marketing',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('community_manager','Community manager freelance',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('copywriter','Copywriter',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('graphiste','Graphiste freelance',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('photographe','Photographe professionnel',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('videaste','Videaste / realisateur',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('webdesigner','Web designer freelance',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('developpeur','Developpeur freelance',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('seo','Consultant SEO',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('ads','Expert publicite digitale',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('influenceur','Createur de contenu',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('podcast','Producteur podcast',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('consultant_marque','Consultant branding / marque',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('rp','Consultant relations presse',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('traducteur','Traducteur / interprete',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('veterinaire','Veterinaire liberal',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('toiletteur','Toiletteur animalier',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('educateur_canin','Educateur canin',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('comportementaliste','Comportementaliste animal',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('pet_sitter','Pet sitter',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('wedding_planner','Wedding planner',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('organisateur_events','Organisateur d evenements',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('traiteur','Traiteur independant',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('dj','DJ / Animateur',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('musicien','Musicien / groupe',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('magicien','Magicien / illusionniste',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('comedien','Comedien / animateur',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('personal_chef','Chef cuisinier a domicile',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('cours_cuisine','Cours de cuisine',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('aide_domicile','Aide a domicile',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('garde_enfants','Garde d enfants / nounou',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('assistante_maternelle','Assistante maternelle',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('accompagnement_senior','Accompagnateur senior',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('coach_parentalite','Coach parentalite',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('precepteur','Precepteur / tuteur scolaire',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('plombier','Plombier independant',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('electricien','Electricien independant',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('menuisier','Menuisier / ebeniste',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('peintre','Peintre en batiment',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('jardinier','Jardinier independant',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('serrurier','Serrurier',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('carreleur','Carreleur',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('couvreur','Couvreur',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('cuisiniste','Cuisiniste independant',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('domotique','Installateur domotique',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('infirmier','Infirmier liberal',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('sage_femme','Sage-femme liberale',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('podologue','Podologue',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('audioprothesiste','Audioprothesiste',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('opticien','Opticien independant',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('ergotherapeute','Ergotherapeute',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('consultant_it','Consultant IT',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('data_analyst','Data analyst freelance',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('cybersecurite','Expert cybersecurite',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('ia_consultant','Consultant IA / automatisation',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('no_code','Expert no-code / automation',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('ux_designer','UX / UI designer',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true),
  ('other_custom','Autre metier',ARRAY['Decouverte','Proposition','Prestation','Suivi'],'{}'::jsonb,'{}'::jsonb,true)
ON CONFLICT (sector_id) DO UPDATE
SET
  label = EXCLUDED.label,
  is_active = true,
  updated_at = timezone('utc', now());

COMMIT;
